### ISSUE TITLE
X-mas

### ISSUE THREAD

**Issue by RouxRC** [miroli/frenchy#1]
Pssst: http://www.data.gouv.fr/fr/search/?q=elections+pr%C3%A9sidentielles
#OpenData ;)

**Comment by miroli** [comment]
Haha thanks @RouxRC, I had a feeling it had to be out there somewhere. Oh well, this was a fun little project.

**Comment by RouxRC** [comment]
hehe certainly :)

**Comment by briatte** [comment]
Agreed, nice little project!
